services:
  database:
    image: metakgporg/dob
    container_name: dob
    build: .
    networks:
      metaploy-private-network:
        aliases:
          - postgres-of-babel
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - PGPORT=${DATABASE_PORT}
      - PGHOST=${DATABASE_HOST}
      - DROPBOX_APP_KEY=${DROPBOX_APP_KEY}
      - DROPBOX_APP_SECRET=${DROPBOX_APP_SECRET}
      - DROPBOX_ACCESS_TOKEN=${DROPBOX_ACCESS_TOKEN}
      - DROPBOX_REFRESH_TOKEN=${DROPBOX_REFRESH_TOKEN}
      - SLACK_INCIDENTS_WH_URL=${SLACK_INCIDENTS_WH_URL}
    volumes:
      - db-volume:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/root/backup/run_backup.sh >> /var/log/backups.log 2>&1 || exit 1",
        ]
      interval: 24h
      timeout: 30s
      retries: 5
    restart: always

networks:
  metaploy-private-network:
    external: true
    name: metaploy-private-network

volumes:
  db-volume:
