name: Continuous Deployment Pipeline

on:
    push:
        branches:
            - "main"
        paths:
            - "docker-compose.yml"
            - "Dockerfile"
            - ".github/workflows/deploy.yaml"

jobs:
    dockerhub:
        name: Publish Docker Image(s) to Dockerhub
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: Cache Docker layers for DOB
              uses: actions/cache@v3
              with:
                  path: /tmp/.buildx-cache-dob
                  key: ${{ runner.os }}-buildx-dob-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-buildx-dob-

            - name: Build & Push DOB
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/dob:latest
                  cache-from: type=local,src=/tmp/.buildx-cache-dob
                  cache-to: type=local,dest=/tmp/.buildx-cache-dob-new,mode=max

            - name: Move DOB cache
              run: |
                  rm -rf /tmp/.buildx-cache-dob
                  mv /tmp/.buildx-cache-dob-new /tmp/.buildx-cache-dob

            - name: Cache Docker layers for DOB Backup
              uses: actions/cache@v3
              with:
                  path: /tmp/.buildx-cache-dob-backup
                  key: ${{ runner.os }}-buildx-dob-backup-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-buildx-dob-backup-

            - name: Build & Push DOB Backup
              uses: docker/build-push-action@v5
              with:
                  context: ./backup
                  push: true
                  build-args: PGPASS=${{secrets.PGPASS}}
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/dob-backup:latest
                  cache-from: type=local,src=/tmp/.buildx-cache-dob-backup
                  cache-to: type=local,dest=/tmp/.buildx-cache-dob-backup-new,mode=max

            - name: Move DOB Backup cache
              run: |
                  rm -rf /tmp/.buildx-cache-dob-backup
                  mv /tmp/.buildx-cache-dob-backup-new /tmp/.buildx-cache-dob-backup

    push:
        name: Push Code Stage
        needs: dockerhub
        runs-on: ubuntu-latest

        steps:
            - name: Sync local repo with remote repo
              uses: appleboy/ssh-action@master
              env:
                  PROJECT_DIR: ${{ secrets.PROJECT_DIR }}
              with:
                  host: ${{ secrets.SSH_HOSTNAME }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  passphrase: ${{ secrets.SSH_PRIVATE_KEY_PASSPHRASE }}
                  envs: PROJECT_DIR
                  script_stop: true
                  script: |
                      cd "${PROJECT_DIR}/"
                      sudo git fetch origin
                      sudo git reset --hard origin/main

    pull:
        name: Pull Image Stage
        needs: push
        runs-on: ubuntu-latest

        steps:
            - name: Pull the latest images(s)
              uses: appleboy/ssh-action@master
              env:
                  PROJECT_DIR: ${{ secrets.PROJECT_DIR }}
              with:
                  host: ${{ secrets.SSH_HOSTNAME }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  passphrase: ${{ secrets.SSH_PRIVATE_KEY_PASSPHRASE }}
                  envs: PROJECT_DIR
                  script_stop: true
                  script: |
                      cd "${PROJECT_DIR}/"
                      sudo docker compose pull

    deploy:
        name: Deploy Stage
        needs: pull
        runs-on: ubuntu-latest

        steps:
            - name: Deploy the latest build(s)
              uses: appleboy/ssh-action@master
              env:
                  PROJECT_DIR: ${{ secrets.PROJECT_DIR }}
              with:
                  host: ${{ secrets.SSH_HOSTNAME }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  passphrase: ${{ secrets.SSH_PRIVATE_KEY_PASSPHRASE }}
                  envs: PROJECT_DIR
                  script_stop: true
                  script: |
                      cd "${PROJECT_DIR}/"
                      sudo docker compose down
                      sudo docker compose up -d
